export const chars = [
    {
        ava: 'https://cdn.pixabay.com/photo/2023/02/05/12/03/cyberpunk-7769321_960_720.jpg',
        name: 'Ex Ample',
        role: 'Rocker',
        special: 'Special',
        int: 6,
        rea: 7,
        dex: 8,
        tech: 6,
        cha: 9,
        will: 12,
        luck: 14,
        move: 8,
        body: 10,
        emp: 8,
        hum: 10,
    },

    {
        name: 'Shnider',
        role: 'Fixer',
        body: 12,
        move: 10,
        ref: 6,
        dex: 10,
        tech: 8,
        cool: 8,
        emp: 10,
        int: 12,
        will: 10,
        luck: 8,
    },

]